import { strToU8, unzipSync, zipSync } from 'fflate';

const STORAGE = 'nai-flow-v1';
const dims = { portrait:[832,1216], square:[1024,1024], landscape:[1216,832], wide:[1536,864] };
const defaultState = {
  projectName:'夏末的信', view:'studio', prompt:`1girl, solo, summer dress, standing on a quiet railway platform, cowboy shot, looking away, sunset, warm backlighting\n\nA light breeze lifts the hem of her dress as the departing train leaves a ribbon of reflected gold across the empty rails. The platform sign is partially cropped at the frame edge; the mood is a quiet goodbye.`,
  negative:'', characters:['girl, long black hair, brown eyes, white summer dress'], model:'nai-diffusion-5-full', aspect:'portrait', samples:'1', steps:28, guidance:5, sampler:'k_euler_ancestral', seed:'', variety:false,
  synopsis:'盛夏最后一天，喜欢画画的澪在废弃的海边车站发现一封来自未来的信。她带着总是迟到的青梅竹马悠，沿着信里的线索赶上落日前最后一班列车。', comicCharacters:'澪：黑色长发、白色夏裙；悠：短棕发、浅色衬衫', pageCount:4, panelCount:4, pages:[], assets:[]
};
let state = loadState(); let lastImageUrl = ''; let toastTimer; let projectSaveTimer; let projectHydrated = false; let imageGenerationActive = false; let allPagesRunning = false; let serverState = { nai:{configured:false,endpoint:'https://image.novelai.net/ai/generate-image'}, llm:{configured:false,endpoint:'',model:''} };
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function loadState(){try{const stored=JSON.parse(localStorage.getItem(STORAGE))||{};delete stored.settings;localStorage.setItem(STORAGE,JSON.stringify(stored));return {...defaultState,...stored,assets:[]}}catch{return structuredClone(defaultState)}}
function persistedAssetUrl(src){return typeof src==='string'&&src.startsWith('/api/assets/')}
function projectSnapshot(){return {...state,assets:state.assets.filter(asset=>persistedAssetUrl(asset.src)),pages:state.pages.map(({title,beat,panels,pagePrompt,image})=>({title,beat,panels,pagePrompt,image:persistedAssetUrl(image)?image:''}))}}
async function persistProject(){if(!projectHydrated||location.protocol==='file:')return;try{const res=await fetch('/api/project',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:projectSnapshot()})});if(!res.ok)throw new Error(await readApiError(res));$('#saveState').textContent='已保存到本机后端'}catch(error){$('#saveState').textContent='后端保存失败（本机缓存仍保留）'}}
function scheduleProjectSave(){if(!projectHydrated)return;clearTimeout(projectSaveTimer);$('#saveState').textContent='正在保存…';projectSaveTimer=setTimeout(persistProject,450)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(projectSnapshot())); scheduleProjectSave(); $('#saveState').textContent=projectHydrated?'正在保存…':'已保存在此设备'}
function toast(message){clearTimeout(toastTimer); const t=$('#toast'); t.textContent=message;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function showLlmError(message){const panel=$('#llmErrorPanel');$('#llmErrorContent').textContent=message;panel.hidden=false;panel.open=true}
function clearLlmError(){const panel=$('#llmErrorPanel');$('#llmErrorContent').textContent='';panel.hidden=true;panel.open=false}
function showImageError(message){const panel=$('#imageErrorPanel');$('#imageErrorContent').textContent=message;panel.hidden=false;panel.open=true}
function clearImageError(){const panel=$('#imageErrorPanel');$('#imageErrorContent').textContent='';panel.hidden=true;panel.open=false}
function escapeHtml(str=''){return str.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function randomSeed(){return String(Math.floor(Math.random()*2147483647))}
function setView(view){state.view=view;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));const labels={studio:['IMAGE STUDIO','基础图片生成'],comic:['STORY WORKFLOW','多页本子生成'],assets:['ASSET LIBRARY','成品与素材']};$('#viewKicker').textContent=labels[view][0];$('#viewTitle').textContent=labels[view][1];save()}
function syncInputs(){
  $('#projectNameSide').textContent=state.projectName; $('#promptInput').value=state.prompt; $('#negativeInput').value=state.negative; $('#modelSelect').value=state.model;$('#aspectSelect').value=state.aspect;$('#sampleCount').value=state.samples;$('#steps').value=state.steps;$('#guidance').value=state.guidance;$('#sampler').value=state.sampler;$('#seed').value=state.seed;
  $('#synopsisInput').value=state.synopsis;$('#comicCharacters').value=state.comicCharacters;$('#pageCount').value=state.pageCount;$('#panelCount').value=state.panelCount;
  $('#naiToken').value='';$('#naiToken').placeholder=serverState.nai.configured?'已配置；留空不覆盖':'pst-… 或你的 Bearer Token';$('#naiEndpoint').value=serverState.nai.endpoint||'https://image.novelai.net/ai/generate-image';$('#llmEndpoint').value=serverState.llm.endpoint||'';$('#llmToken').value='';$('#llmToken').placeholder=serverState.llm.configured?'已配置；留空不覆盖':'sk-…';$('#llmModel').value=serverState.llm.model||'';
  updateParameterLabels();renderCharacters();renderPages();renderAssets();renderPageTree();connectionLabel();setView(state.view);
}
function updateParameterLabels(){const d=dims[state.aspect];$('#dimensionText').textContent=`${d[0]} × ${d[1]} px`;$('#stepsValue').textContent=state.steps;$('#guidanceValue').textContent=Number(state.guidance).toFixed(1);$('#promptLength').textContent=`${state.prompt.length} chars`;}
function renderCharacters(){const list=$('#characterList');list.innerHTML=state.characters.map((c,i)=>`<div class="character-card"><span class="character-index">${String(i+1).padStart(2,'0')}</span><input data-char="${i}" value="${escapeHtml(c)}" aria-label="角色 ${i+1} 提示词"/><button class="text-button delete-character" data-delete-char="${i}" title="删除角色">×</button></div>`).join('');}
function renderPageTree(){const el=$('#pageTree');el.innerHTML=state.pages.map((p,i)=>`<button data-page-select="${i}" class="${i===0?'active':''}">▱ ${p.title||`第 ${i+1} 页`}</button>`).join('')||'<span style="color:#635e6b;font-size:11px;padding:6px">暂无分镜页面</span>'}
function renderPages(){const grid=$('#pagesGrid');$('#pageHeading').textContent=state.pages.length?`${state.pages.length} 页 · 连续分镜`:'等待剧本';if(!state.pages.length){grid.innerHTML='<div class="empty-pages"><span>▦</span><h3>从一句故事开始</h3><p>系统会将剧情拆成连续页面，再按每页分格生成 NovelAI V5 提示词。</p></div>';return}grid.innerHTML=state.pages.map((p,i)=>`<article class="page-card"><div class="page-thumb">${p.image?`<img src="${p.image}" alt="${escapeHtml(p.title)}"/>`:'▦'}</div><div class="page-info"><h3>第 ${i+1} 页 · ${escapeHtml(p.title)}</h3><p>${escapeHtml(p.beat)}</p><details><summary>查看 ${p.panels.length} 格分镜与提示词</summary><div class="panel-lines">${p.panels.map((x,n)=>`${n+1}. ${x}`).join('\n')}</div><button class="text-button edit-page" data-edit-page="${i}">编辑整页提示词</button></details><div class="page-actions"><button class="button ghost" data-copy-page="${i}">复制提示词</button><button class="button" data-generate-page="${i}">${p.loading?'生成中…':'生成本页'}</button></div></div></article>`).join('')}
function renderAssets(){const grid=$('#assetGrid');$('#assetCount').textContent=state.assets.length;if(!state.assets.length){grid.innerHTML='<div class="empty-pages"><span>◫</span><h3>还没有成品</h3><p>基础出图和本子页面都会自动收集到这里。</p></div>';return}grid.innerHTML=state.assets.map((a,i)=>`<article class="asset-card"><img src="${a.src}" alt="${escapeHtml(a.title)}"/><footer><span>${escapeHtml(a.title)}</span><button class="text-button" data-download-asset="${i}">下载</button></footer></article>`).join('')}
function connectionLabel(){const c=$('#connectionState');c.textContent=serverState.nai.configured?'NovelAI 已配置':'后端未配置 NovelAI';$('.settings-dot').style.color=serverState.nai.configured?'#85d8b2':'#7b6a92'}
async function readApiError(res){try{const body=await res.json();return body.detail||body.error||`${res.status} 请求失败`}catch{return `${res.status} 请求失败`}}
async function refreshBackendStatus(){if(location.protocol==='file:'){toast('请通过 npm run dev 启动前端，不要直接打开 HTML');return}try{const res=await fetch('/api/health');if(!res.ok)throw new Error(await readApiError(res));serverState=await res.json();syncInputs()}catch(error){connectionLabel();toast(`后端不可用：${error.message||error}`)}}
async function loadServerProject(){if(location.protocol==='file:'){projectHydrated=true;return}try{const res=await fetch('/api/project');if(res.status===404){projectHydrated=true;scheduleProjectSave();return}if(!res.ok)throw new Error(await readApiError(res));const project=(await res.json()).state;if(!project||typeof project!=='object')throw new Error('项目数据无效');state={...defaultState,...project,assets:Array.isArray(project.assets)?project.assets:[]};localStorage.setItem(STORAGE,JSON.stringify(projectSnapshot()));projectHydrated=true;syncInputs();$('#saveState').textContent='已从本机后端恢复'}catch(error){projectHydrated=true;$('#saveState').textContent='后端项目读取失败，使用浏览器缓存';toast(`项目恢复失败：${error.message||error}`)}}
function collectParams(){const chars=state.characters.filter(Boolean);const centers=chars.map((_,index)=>({x:chars.length===1?.5:.2+index*.6/(chars.length-1),y:.5}));const negative=state.negative.trim();return {params_version:4,width:dims[state.aspect][0],height:dims[state.aspect][1],scale:Number(state.guidance),sampler:state.sampler,steps:Number(state.steps),n_samples:Number(state.samples),seed:state.seed?Number(state.seed):Math.floor(Math.random()*4294967295),negative_prompt:negative,uc:negative,ucPreset:0,qualityToggle:true,legacy:false,legacy_v3_extend:false,add_original_image:true,cfg_rescale:0,noise_schedule:'karras',v4_prompt:{caption:{base_caption:state.prompt,char_captions:chars.map((char_caption,index)=>({char_caption,centers:[centers[index]]}))},use_coords:chars.length>1,use_order:true,legacy_uc:false},v4_negative_prompt:{caption:{base_caption:negative,char_captions:chars.map((_,index)=>({char_caption:negative,centers:[centers[index]]}))},use_coords:false,use_order:false,legacy_uc:false}}}
function unzipImages(buffer){try{const entries=unzipSync(new Uint8Array(buffer));const images=Object.entries(entries).filter(([name])=>/\.(png|webp|jpe?g)$/i.test(name)).map(([name,bytes])=>new Blob([bytes],{type:/\.png$/i.test(name)?'image/png':/\.webp$/i.test(name)?'image/webp':'image/jpeg'}));if(!images.length)throw new Error('压缩包中没有可用图片文件');return images}catch(error){throw new Error(`无法解包 NovelAI 图片结果：${error.message||error}`)}}
async function generateImage({prompt=state.prompt,characters=state.characters,title='基础出图'}={}){if(imageGenerationActive)throw new Error('已有图片任务正在生成，请等待当前任务结束后再提交。');if(!serverState.nai.configured){$('#settingsDialog').showModal();toast('请先在后端连接设置中保存 NovelAI Token');throw new Error('后端未配置 NovelAI Token')}const oldPrompt=state.prompt,oldChars=state.characters;state.prompt=prompt;state.characters=characters;const params=collectParams();state.prompt=oldPrompt;state.characters=oldChars;const button=$('#generateButton');imageGenerationActive=true;clearImageError();button.disabled=true;button.textContent='正在生成…';try{const res=await fetch('/api/generate/image',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/zip'},body:JSON.stringify({input:prompt,model:state.model,parameters:params})});if(!res.ok){let message=await readApiError(res);if(res.status===429){const retry=res.headers.get('Retry-After');message=`${message}${retry?`\n\n请等待 ${retry} 秒再继续。`:''}`}throw new Error(message)}const type=res.headers.get('content-type')||'';const blobs=type.includes('image/')?[await res.blob()]:await unzipImages(await res.arrayBuffer());const urls=blobs.map(blob=>URL.createObjectURL(blob));return {url:urls[0],urls,blobs,title,seed:params.seed}}catch(error){const message=error.message||'生成失败';showImageError(message);toast(message);throw error}finally{imageGenerationActive=false;button.disabled=false;button.innerHTML='<span>✦</span> 生成图片 <kbd>⌘ ↵</kbd>'}}
async function persistImageAsset(blob){const res=await fetch('/api/assets/image',{method:'POST',headers:{'Content-Type':blob.type||'image/png'},body:blob});if(!res.ok)throw new Error(await readApiError(res));const payload=await res.json();if(!persistedAssetUrl(payload.url))throw new Error('后端未返回有效素材地址');return payload.url}
async function persistImages(blobs){return Promise.all(blobs.map(persistImageAsset))}
async function basicGenerate(){try{const result=await generateImage();let urls;try{urls=await persistImages(result.blobs)}catch(error){urls=result.urls;toast(`图片已生成，但保存到本机失败：${error.message||error}`)}if(lastImageUrl&&lastImageUrl.startsWith('blob:'))URL.revokeObjectURL(lastImageUrl);lastImageUrl=urls[0];$('#generatedImage').src=urls[0];$('#generatedImage').hidden=false;$('#emptyArt').hidden=true;$('#generationMeta').textContent=`${dims[state.aspect].join(' × ')} · seed ${result.seed}`;$('#downloadImage').disabled=false;$('#useAsReference').disabled=false;state.assets.unshift(...urls.map((src,i)=>({src,title:`基础图${urls.length>1?` ${i+1}`:''} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`})));save();renderAssets();toast(urls.length>1?`已生成 ${urls.length} 张并保存到本机素材库`:'图片已生成并保存到本机素材库')}catch{}}
function getComicRoles(){const raw=state.comicCharacters.trim();if(!raw)return [];let entries=raw.split(/[；;\n]/).map(x=>x.trim()).filter(Boolean);if(entries.length===1&&!raw.includes('：'))entries=raw.split(/[，,]/).map(x=>x.trim()).filter(Boolean);return entries.map((entry,index)=>{const pivot=entry.indexOf('：');const name=(pivot>=0?entry.slice(0,pivot):entry).trim();const appearance=(pivot>=0?entry.slice(pivot+1):'').trim();return {index:index+1,name:name||`角色 ${index+1}`,appearance}})}
function characterCaption(role){return `girl, ${role.appearance||role.name}`}
function panelAnchor(index){return ['Top-left','Top-right','Bottom-left','Bottom-right','Panel '+(index+1)][index]||'Panel '+(index+1)}
function withPanelAnchor(panel,index){const clean=panel.replace(/^\s*(top-left|top-right|bottom-left|bottom-right|panel\s+\d+)\s*[:;]\s*/i,'');return `${panelAnchor(index)}: ${clean}`}
function promptForPage(page,includeCharacterSheet=false){const roles=getComicRoles();const count=roles.length||1;const countTag=count===1?'1girl, solo':`${count}girls`;const panels=page.panels.map(withPanelAnchor).join(' ');const identity=roles.length>1?`${roles.map(role=>`Character ${role.index}`).join(' and ')} appear in every panel with consistent identities and clothing.`:'Character 1 remains visually consistent across all panels.';const base=`${countTag}, ${page.panels.length}-panel manga-style page, equal clean panel borders, continuous visual storytelling, comic. ${panels} ${identity} ${page.pagePrompt||''}`.trim();if(!includeCharacterSheet)return base;const sheet=roles.length?roles.map(role=>`Character ${role.index}: ${characterCaption(role)}`).join('\n'):'Character 1: girl';return `${base}\n\n${sheet}`}
function parseCharacterPrompts(){const roles=getComicRoles();return roles.length?roles.map(characterCaption):state.characters.filter(Boolean)}
async function resolveComicCharacters(){const raw=state.comicCharacters.trim();if(!raw){toast('请先输入中文角色名');return}const button=$('#resolveCharacters');button.disabled=true;button.textContent='正在识别…';try{const res=await fetch('/api/resolve/characters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({characters:raw})});if(!res.ok)throw new Error(await readApiError(res));const resolved=(await res.json()).characters||[];const mapped=resolved.map(item=>{const label=item.input||item.english_name;const canonical=item.nai_character||[item.english_name,item.series&&`(${item.series})`].filter(Boolean).join(' ');return `${label}: ${canonical}`}).filter(x=>!x.endsWith(': '));if(!mapped.length)throw new Error('未识别到可用角色');state.comicCharacters=mapped.join('；');$('#comicCharacters').value=state.comicCharacters;const uncertain=resolved.filter(item=>item.confidence!=='high').length;$('#characterResolveHint').textContent=uncertain?`已写入 ${mapped.length} 个映射；其中 ${uncertain} 个不确定，请检查后再生成。`:`已写入 ${mapped.length} 个英文名与出处映射，会同时提供给 LLM 和 NovelAI Character 字段。`;save();toast('角色英文名与出处已写入，可手动编辑')}catch(error){toast(error.message||'角色名称识别失败')}finally{button.disabled=false;button.textContent='识别英文名与出处'}}
async function generatePage(index){const page=state.pages[index];if(!page||page.loading)return;if(imageGenerationActive){toast('已有图片任务正在生成，请等待后再提交。');return}page.loading=true;renderPages();try{const result=await generateImage({prompt:promptForPage(page),characters:parseCharacterPrompts(),title:`第 ${index+1} 页 · ${page.title}`});try{page.image=await persistImageAsset(result.blobs[0]);state.assets.unshift({src:page.image,title:`本子 · 第 ${index+1} 页`});toast(`第 ${index+1} 页已生成并保存到本机`)}catch(error){page.image=result.url;state.assets.unshift({src:result.url,title:`本子 · 第 ${index+1} 页`});toast(`第 ${index+1} 页已生成，但保存到本机失败：${error.message||error}`)}}catch{}finally{page.loading=false;save();renderPages();renderAssets()}}
async function generateAllPages(){if(!state.pages.length){toast('请先生成剧本');return}if(allPagesRunning){toast('全页生成任务正在运行，请勿重复提交。');return}allPagesRunning=true;try{for(let i=0;i<state.pages.length;i++)await generatePage(i)}finally{allPagesRunning=false}}
function localStoryboard(){const count=Number(state.pageCount), panels=Number(state.panelCount);const chars=state.comicCharacters.split(/[；;，,]/).map(x=>x.trim()).filter(Boolean);const lead=chars[0]?.split('：')[0]||'少女', partner=chars[1]?.split('：')[0]||'同伴';const beats=[['发现信件',`${lead} 在安静的海边车站发现一封褪色的信，故事开始出现异常。`,[`wide shot, ${lead} standing alone on a deserted seaside station platform, sunset`,`${lead} notices an old envelope tucked under a bench, surprised expression`,`close-up, a handwritten date on the envelope, ocean light reflected on paper`,`${lead} looks down the tracks, wind lifting hair, determined expression`]],['约定同行',`${partner} 赶到车站，两人决定按信中的线索追赶最后一班车。`,[`${partner} running into frame from the station stairs, motion blur`,`${lead} shows the letter to ${partner}, two characters facing each other`,`source#pointing at the timetable, target#looking at the letter, old station clock`,`both characters run along the platform, long evening shadows`]],['追赶列车',`线索指向远处的列车，两人穿过被夕阳照亮的站台。`,[`low angle, train entering the distant platform, dramatic perspective`,`${lead} reaches toward ${partner}, hands almost touching`,`${partner} pulls ${lead} forward, source#holding hand, warm backlighting`,`wide shot, both characters small against a glowing sea and rails`]],['未来的回信',`列车离开后，信的最后一页揭示这是留给此刻自己的回信。`,[`inside the train, ${lead} and ${partner} sit side by side by the window`,`close-up, the final line of the letter glowing in sunset light`,`${lead} smiles with tears in her eyes, ${partner} looking gently at her`,`wide shot, train fading into sunset over the sea, large negative space`]]];return Array.from({length:count},(_,i)=>{const b=beats[i%beats.length];let ps=b[2];if(panels<4)ps=ps.slice(0,panels);if(panels>4)ps=[...ps,...Array.from({length:panels-4},(_,j)=>`transition shot ${j+1}, quiet environmental detail that connects the previous and next moment`)];return {title:b[0],beat:b[1],panels:ps,pagePrompt:''}})}
function storyboardRoleBindings(){const roles=getComicRoles();return roles.length?roles.map(role=>`Character ${role.index} = ${role.name}; NovelAI Character field = ${characterCaption(role)}`).join('\n'):state.comicCharacters.trim()}
async function llmStoryboard(){if(!serverState.llm.configured)return null;const res=await fetch('/api/generate/script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({synopsis:state.synopsis,characters:storyboardRoleBindings(),pages:Number(state.pageCount),panels:Number(state.panelCount)})});if(res.status===204)return null;if(!res.ok)throw new Error(await readApiError(res));const json=await res.json();if(!Array.isArray(json.pages)||!json.pages.length)throw new Error('剧本文本模型未返回可用 pages JSON');return json.pages.map(p=>({...p,panels:(p.panels||[]).slice(0,Number(state.panelCount)),pagePrompt:''}))}
async function buildScript(){const b=$('#generateScript');clearLlmError();b.disabled=true;b.textContent='正在规划分镜…';try{state.pages=await llmStoryboard()||localStoryboard();save();renderPages();renderPageTree();toast(serverState.llm.configured?'剧本文本模型已生成分镜':'已生成本地分镜初稿，可直接编辑')}catch(e){const message=e.message||'剧本生成失败';showLlmError(message);toast(message)}finally{b.disabled=false;b.innerHTML='<span>✦</span> 生成剧本和分镜'}}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>{if(url.startsWith('blob:'))URL.revokeObjectURL(url)},1000)}
function safeFileName(value='page'){return value.replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').trim().slice(0,80)||'page'}
function imageExtension(mime=''){return mime.includes('webp')?'webp':mime.includes('jpeg')?'jpg':'png'}
async function downloadComicPackage(){if(!state.pages.length){toast('请先生成剧本');return}const button=$('#downloadComicZip');button.disabled=true;button.textContent='正在打包…';try{const files={};const missingImages=[];const manifest={project:state.projectName,exportedAt:new Date().toISOString(),pages:[]};for(let index=0;index<state.pages.length;index++){const page=state.pages[index];const prefix=String(index+1).padStart(2,'0');const name=safeFileName(page.title||`page-${prefix}`);const prompt=promptForPage(page,true);files[`prompts/${prefix}-${name}.txt`]=strToU8(prompt);const item={page:index+1,title:page.title,beat:page.beat,panels:page.panels,prompt,imageIncluded:false};if(page.image){try{const response=await fetch(page.image);if(!response.ok)throw new Error(`${response.status}`);const blob=await response.blob();files[`pages/${prefix}-${name}.${imageExtension(blob.type)}`]=new Uint8Array(await blob.arrayBuffer());item.imageIncluded=true}catch(error){missingImages.push(`第 ${index+1} 页：图片无法读取（${error.message||error}）`)}}else{missingImages.push(`第 ${index+1} 页：尚未生成图片`)}manifest.pages.push(item)}files['storyboard.json']=strToU8(JSON.stringify(manifest,null,2));files['README.txt']=strToU8(`NAI Flow 本子导出包\n\n包含：\n- pages/: 已成功读取的页面图片\n- prompts/: 每页完整 NovelAI V5 提示词（含 Character 字段）\n- storyboard.json: 剧本、分镜和导出清单\n\n${missingImages.length?`未包含图片：\n${missingImages.join('\n')}`:'所有页面图片均已包含。'}\n`);const archive=zipSync(files,{level:6});download(URL.createObjectURL(new Blob([archive],{type:'application/zip'})),`${safeFileName(state.projectName||'nai-flow')}-comic.zip`);toast(`本子包已下载：${state.pages.length-missingImages.length}/${state.pages.length} 页图片，全部提示词已附带`)}catch(error){toast(`打包失败：${error.message||error}`)}finally{button.disabled=false;button.textContent='打包下载'}}
function exportProject(){const blob=new Blob([JSON.stringify({...state,assets:[]},null,2)],{type:'application/json'});download(URL.createObjectURL(blob),`${state.projectName||'nai-flow'}.json`)}
function formatPrompt(){state.prompt=state.prompt.replace(/\s*,\s*/g,', ').replace(/\n{3,}/g,'\n\n').trim();$('#promptInput').value=state.prompt;updateParameterLabels();save();toast('已整理逗号与段落结构')}
function setupEvents(){
  const testNaiConnection=document.createElement('button');testNaiConnection.type='button';testNaiConnection.className='button ghost';testNaiConnection.textContent='测试 NovelAI 连接（不扣额度）';$('#naiSettings').append(testNaiConnection);testNaiConnection.onclick=async()=>{try{const res=await fetch('/api/settings/test/nai',{method:'POST'});if(!res.ok)throw new Error(await readApiError(res));toast((await res.json()).detail)}catch(error){toast(error.message||'NovelAI 连接测试失败')}};
  $$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#promptInput').oninput=e=>{state.prompt=e.target.value;updateParameterLabels();save()};$('#negativeInput').oninput=e=>{state.negative=e.target.value;save()};
  [['modelSelect','model'],['aspectSelect','aspect'],['sampleCount','samples'],['steps','steps'],['guidance','guidance'],['sampler','sampler'],['seed','seed']].forEach(([id,key])=>$('#'+id).oninput=e=>{state[key]=e.target.value;updateParameterLabels();save()});
  $('#characterList').oninput=e=>{if(e.target.dataset.char!==undefined){state.characters[Number(e.target.dataset.char)]=e.target.value;save()}};$('#characterList').onclick=e=>{const i=e.target.dataset.deleteChar;if(i!==undefined){state.characters.splice(Number(i),1);renderCharacters();save()}};$('#addCharacter').onclick=()=>{state.characters.push('girl, ');renderCharacters();save()};
  $('#generateButton').onclick=basicGenerate;$('#randomSeed').onclick=()=>{state.seed=randomSeed();$('#seed').value=state.seed;save()};$('#resetParameters').onclick=()=>{Object.assign(state,{model:defaultState.model,aspect:defaultState.aspect,samples:'1',steps:28,guidance:5,sampler:'k_euler_ancestral',seed:'',variety:false,negative:''});syncInputs();save();toast('参数已重置')};$('#formatPrompt').onclick=formatPrompt;
  $('#downloadImage').onclick=()=>lastImageUrl&&download(lastImageUrl,'nai-flow.png');$('#useAsReference').onclick=()=>toast('参考图模式预留：当前版本已保留结果，后续可接 i2i 参数');
  $('#synopsisInput').oninput=e=>{state.synopsis=e.target.value;save()};$('#comicCharacters').oninput=e=>{state.comicCharacters=e.target.value;save()};$('#resolveCharacters').onclick=resolveComicCharacters;$('#pageCount').onchange=e=>{state.pageCount=e.target.value;save()};$('#panelCount').onchange=e=>{state.panelCount=e.target.value;save()};$('#generateScript').onclick=buildScript;$('#regenerateScript').onclick=buildScript;$('#downloadComicZip').onclick=downloadComicPackage;$('#generateAllPages').onclick=generateAllPages;
  $('#pagesGrid').onclick=e=>{const g=e.target.dataset.generatePage,c=e.target.dataset.copyPage,edit=e.target.dataset.editPage;if(g!==undefined)generatePage(Number(g));if(c!==undefined){navigator.clipboard.writeText(promptForPage(state.pages[Number(c)],true));toast('整页提示词与角色表已复制')}if(edit!==undefined){const p=state.pages[Number(edit)],value=prompt('编辑本页附加提示词（将附在分格描述之后）',p.pagePrompt||'');if(value!==null){p.pagePrompt=value;save();renderPages()}}};
  $('#openSettings').onclick=()=>$('#settingsDialog').showModal();$('#showHelp').onclick=()=>$('#helpDialog').showModal();$$('.settings-tab').forEach(b=>b.onclick=()=>{$$('.settings-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.settings-content').forEach(x=>x.classList.toggle('active',x.id===b.dataset.settings+'Settings'))});$('#saveSettings').onclick=async e=>{e.preventDefault();try{const res=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nai:{token:$('#naiToken').value.trim()||undefined,endpoint:$('#naiEndpoint').value.trim()},llm:{token:$('#llmToken').value.trim()||undefined,endpoint:$('#llmEndpoint').value.trim(),model:$('#llmModel').value.trim()}})});if(!res.ok)throw new Error(await readApiError(res));serverState=await res.json();syncInputs();$('#settingsDialog').close();toast('连接设置已保存到本机后端')}catch(error){toast(error.message||'保存设置失败')}};
  $('#renameProject').onclick=()=>{const v=prompt('项目名称',state.projectName);if(v?.trim()){state.projectName=v.trim();syncInputs();save()}};$('#addPage').onclick=()=>{state.pages.push({title:'新页面',beat:'等待补充分镜内容。',panels:['Panel 1 visual direction','Panel 2 visual direction','Panel 3 visual direction','Panel 4 visual direction'],pagePrompt:''});save();renderPages();renderPageTree()};$('#clearAssets').onclick=()=>{if(confirm('只清空浏览器中的预览记录，是否继续？')){state.assets=[];save();renderAssets();toast('已清空本地预览')}};
  $('#exportProject').onclick=exportProject;$('#importProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());delete imported.settings;state={...defaultState,...imported,assets:[]};save();syncInputs();toast('项目已导入')}catch{toast('项目文件无效')}};
  $('#assetGrid').onclick=e=>{const i=e.target.dataset.downloadAsset;if(i!==undefined)download(state.assets[Number(i)].src,'nai-flow-asset.png')};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();basicGenerate()}});
}
syncInputs();setupEvents();refreshBackendStatus();loadServerProject();
