import { strToU8, unzipSync, zipSync } from 'fflate';

const STORAGE = 'nai-flow-v1';
const dims = { portrait:[832,1216], square:[1024,1024], landscape:[1216,832], wide:[1536,864] };
const defaultState = {
  projectName:'夏末的信', view:'studio', prompt:`1girl, solo, summer dress, standing on a quiet railway platform, cowboy shot, looking away, sunset, warm backlighting\n\nA light breeze lifts the hem of her dress as the departing train leaves a ribbon of reflected gold across the empty rails. The platform sign is partially cropped at the frame edge; the mood is a quiet goodbye.`,
  negative:'', characters:['girl, long black hair, brown eyes, white summer dress'], model:'nai-diffusion-5-full', aspect:'portrait', samples:'1', steps:28, guidance:5, sampler:'k_euler_ancestral', seed:'', variety:false,
  synopsis:'盛夏最后一天，喜欢画画的澪在废弃的海边车站发现一封来自未来的信。她带着总是迟到的青梅竹马悠，沿着信里的线索赶上落日前最后一班列车。', comicCharacters:'澪：黑色长发、白色夏裙；悠：短棕发、浅色衬衫', comicStyle:'colored manga, crisp lineart, late-summer coastal railway, warm sunset light', continuityAnchor:'褪色的信封、站台通向列车的移动方向、逐渐变暗的夕阳', characterPlacement:'ai', pageCount:4, panelCount:4, pages:[], assets:[]
};
let state = loadState(); let lastImageUrl = ''; let toastTimer; let projectSaveTimer; let projectHydrated = false; let projectSaveInFlight = false; let projectSaveQueued = false; let imageGenerationActive = false; let allPagesRunning = false; let selectedPageIndex = 0; let serverState = { nai:{configured:false,endpoint:'https://image.novelai.net/ai/generate-image'}, llm:{configured:false,endpoint:'',model:''} };
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function loadState(){try{const stored=JSON.parse(localStorage.getItem(STORAGE))||{};delete stored.settings;return normalizeProject(stored,{keepAssets:false})}catch{return structuredClone(defaultState)}}
function persistedAssetUrl(src){return typeof src==='string'&&src.startsWith('/api/assets/')}
function isSafeImageUrl(src,{allowBlob=true}={}){return persistedAssetUrl(src)||(allowBlob&&typeof src==='string'&&src.startsWith('blob:'))}
function normalizePage(page={},{allowBlob=false}={}){const panels=Array.isArray(page.panels)?page.panels.slice(0,9).filter(panel=>typeof panel==='string').map(panel=>panel.slice(0,10000)):[];return {title:typeof page.title==='string'?page.title.slice(0,300):'新页面',beat:typeof page.beat==='string'?page.beat.slice(0,4000):'',continuity:typeof page.continuity==='string'?page.continuity.slice(0,2000):'',panels,pagePrompt:typeof page.pagePrompt==='string'?page.pagePrompt.slice(0,10000):'',image:isSafeImageUrl(page.image,{allowBlob})?page.image:''}}
function normalizeProject(raw,{keepAssets=true,allowBlob=false}={}){if(!raw||typeof raw!=='object')throw new Error('项目文件不是有效对象');const next={...defaultState,...raw};next.view=['studio','comic','assets'].includes(next.view)?next.view:defaultState.view;next.aspect=dims[next.aspect]?next.aspect:defaultState.aspect;next.characterPlacement=['ai','left-right'].includes(next.characterPlacement)?next.characterPlacement:'ai';next.comicStyle=typeof next.comicStyle==='string'?next.comicStyle.slice(0,4000):'';next.continuityAnchor=typeof next.continuityAnchor==='string'?next.continuityAnchor.slice(0,4000):'';next.characters=Array.isArray(raw.characters)?raw.characters.filter(value=>typeof value==='string').slice(0,10):[...defaultState.characters];next.pages=Array.isArray(raw.pages)?raw.pages.slice(0,20).map(page=>normalizePage(page,{allowBlob})):[];next.assets=keepAssets&&Array.isArray(raw.assets)?raw.assets.filter(asset=>asset&&typeof asset.title==='string'&&isSafeImageUrl(asset.src,{allowBlob})).slice(0,200).map(asset=>({src:asset.src,title:asset.title.slice(0,300)})):[];return next}
function projectSnapshot(){return {...state,assets:state.assets.filter(asset=>persistedAssetUrl(asset.src)),pages:state.pages.map(page=>normalizePage(page))}}
async function persistProject(){if(!projectHydrated||location.protocol==='file:')return;if(projectSaveInFlight){projectSaveQueued=true;return}projectSaveInFlight=true;const snapshot=projectSnapshot();try{const res=await fetch('/api/project',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:snapshot})});if(!res.ok)throw new Error(await readApiError(res));$('#saveState').textContent='已保存到本机后端'}catch(error){$('#saveState').textContent='后端保存失败（本机缓存仍保留）'}finally{projectSaveInFlight=false;if(projectSaveQueued){projectSaveQueued=false;persistProject()}}}
function scheduleProjectSave(){if(!projectHydrated)return;clearTimeout(projectSaveTimer);$('#saveState').textContent='正在保存…';projectSaveTimer=setTimeout(persistProject,450)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(projectSnapshot())); scheduleProjectSave(); $('#saveState').textContent=projectHydrated?'正在保存…':'已保存在此设备'}
function toast(message){clearTimeout(toastTimer); const t=$('#toast'); t.textContent=message;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function showLlmError(message){const panel=$('#llmErrorPanel');$('#llmErrorContent').textContent=message;panel.hidden=false;panel.open=true}
function clearLlmError(){const panel=$('#llmErrorPanel');$('#llmErrorContent').textContent='';panel.hidden=true;panel.open=false}
function showImageError(message){const panel=$('#imageErrorPanel');$('#imageErrorContent').textContent=message;panel.hidden=false;panel.open=true}
function clearImageError(){const panel=$('#imageErrorPanel');$('#imageErrorContent').textContent='';panel.hidden=true;panel.open=false}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function randomSeed(){return String(Math.floor(Math.random()*2147483647))}
function setView(view,persist=true){state.view=view;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));const labels={studio:['IMAGE STUDIO','基础图片生成'],comic:['STORY WORKFLOW','多页本子生成'],assets:['ASSET LIBRARY','成品与素材']};$('#viewKicker').textContent=labels[view][0];$('#viewTitle').textContent=labels[view][1];if(persist)save()}
function syncInputs(){
  $('#projectNameSide').textContent=state.projectName; $('#promptInput').value=state.prompt; $('#negativeInput').value=state.negative; $('#modelSelect').value=state.model;$('#aspectSelect').value=state.aspect;$('#sampleCount').value=state.samples;$('#steps').value=state.steps;$('#guidance').value=state.guidance;$('#sampler').value=state.sampler;$('#seed').value=state.seed;
  $('#synopsisInput').value=state.synopsis;$('#comicCharacters').value=state.comicCharacters;$('#comicStyle').value=state.comicStyle;$('#continuityAnchor').value=state.continuityAnchor;$('#characterPlacement').value=state.characterPlacement;$('#pageCount').value=state.pageCount;$('#panelCount').value=state.panelCount;
  $('#naiToken').value='';$('#naiToken').placeholder=serverState.nai.configured?'已配置；留空不覆盖':'pst-… 或你的 Bearer Token';$('#naiEndpoint').value=serverState.nai.endpoint||'https://image.novelai.net/ai/generate-image';$('#llmEndpoint').value=serverState.llm.endpoint||'';$('#llmToken').value='';$('#llmToken').placeholder=serverState.llm.configured?'已配置；留空不覆盖':'sk-…';$('#llmModel').value=serverState.llm.model||'';
  updateParameterLabels();renderCharacters();renderPages();renderAssets();renderPageTree();connectionLabel();setView(state.view,false);
}
function updateParameterLabels(){const d=dims[state.aspect];$('#dimensionText').textContent=`${d[0]} × ${d[1]} px`;$('#stepsValue').textContent=state.steps;$('#guidanceValue').textContent=Number(state.guidance).toFixed(1);$('#promptLength').textContent=`${state.prompt.length} chars`;}
function renderCharacters(){const list=$('#characterList');list.innerHTML=state.characters.map((c,i)=>`<div class="character-card"><span class="character-index">${String(i+1).padStart(2,'0')}</span><input data-char="${i}" value="${escapeHtml(c)}" aria-label="角色 ${i+1} 提示词"/><button class="text-button delete-character" data-delete-char="${i}" title="删除角色">×</button></div>`).join('');}
function renderPageTree(){const el=$('#pageTree');el.innerHTML=state.pages.map((p,i)=>`<button data-page-select="${i}" class="${i===selectedPageIndex?'active':''}">▱ ${escapeHtml(p.title||`第 ${i+1} 页`)}</button>`).join('')||'<span style="color:#635e6b;font-size:11px;padding:6px">暂无分镜页面</span>'}
function pagePromptReview(page){const panels=Array.isArray(page.panels)?page.panels:[];const roles=getComicRoles();const issues=[];if(!panels.length)issues.push('缺少分镜');if(panels.some(panel=>/\b(?:then|cut to|meanwhile|montage)\b/i.test(panel)))issues.push('含有多时刻/转场词');if(roles.length&&panels.some(panel=>!new RegExp('Character\\s+[1-9]', 'i').test(panel)))issues.push('至少一格未使用 Character 编号');if(roles.some(role=>role.name&&panels.some(panel=>panel.includes(role.name))))issues.push('分镜中泄漏了角色名称');return issues}
function renderPages(){const grid=$('#pagesGrid');$('#pageHeading').textContent=state.pages.length?`${state.pages.length} 页 · 连续分镜`:'等待剧本';if(!state.pages.length){grid.innerHTML='<div class="empty-pages"><span>▦</span><h3>从一句故事开始</h3><p>系统会将剧情拆成连续页面，再按每页分格生成 NovelAI V5 提示词。</p></div>';return}grid.innerHTML=state.pages.map((p,i)=>{const panels=Array.isArray(p.panels)?p.panels:[];const image=isSafeImageUrl(p.image)?escapeHtml(p.image):'';const issues=pagePromptReview(p);const review=issues.length?`⚠ Prompt 检查：${escapeHtml(issues.join('；'))}`:'✓ Prompt 检查通过：角色编号、定格与连续性可用';return `<article class="page-card" data-page-card="${i}"><div class="page-thumb">${image?`<img src="${image}" alt="${escapeHtml(p.title)}"/>`:'▦'}</div><div class="page-info"><h3>第 ${i+1} 页 · ${escapeHtml(p.title)}</h3><p>${escapeHtml(p.beat)}</p>${p.continuity?`<p class="hint">连续性：${escapeHtml(p.continuity)}</p>`:''}<p class="hint">${review}</p><details><summary>查看 ${panels.length} 格分镜与提示词</summary><div class="panel-lines">${panels.map((x,n)=>`${n+1}. ${escapeHtml(x)}`).join('\n')}</div><button class="text-button edit-storyboard" data-edit-storyboard="${i}">编辑标题与分镜</button><button class="text-button edit-page" data-edit-page="${i}">编辑整页附加提示词</button></details><div class="page-actions"><button class="button ghost" data-copy-page="${i}">复制提示词</button><button class="button" data-generate-page="${i}">${p.loading?'生成中…':'生成本页'}</button></div></div></article>`}).join('')}
function renderAssets(){const assets=state.assets.filter(asset=>isSafeImageUrl(asset.src));const grid=$('#assetGrid');$('#assetCount').textContent=assets.length;if(!assets.length){grid.innerHTML='<div class="empty-pages"><span>◫</span><h3>还没有成品</h3><p>基础出图和本子页面都会自动收集到这里。</p></div>';return}grid.innerHTML=assets.map((a,i)=>`<article class="asset-card"><img src="${escapeHtml(a.src)}" alt="${escapeHtml(a.title)}"/><footer><span>${escapeHtml(a.title)}</span><button class="text-button" data-download-asset="${i}">下载</button></footer></article>`).join('')}
function connectionLabel(){const c=$('#connectionState');c.textContent=serverState.nai.configured?'NovelAI 已配置':'后端未配置 NovelAI';$('.settings-dot').style.color=serverState.nai.configured?'#85d8b2':'#7b6a92'}
async function readApiError(res){try{const body=await res.json();return body.detail||body.error||`${res.status} 请求失败`}catch{return `${res.status} 请求失败`}}
async function refreshBackendStatus(){if(location.protocol==='file:'){toast('请通过 npm run dev 启动前端，不要直接打开 HTML');return}try{const res=await fetch('/api/health');if(!res.ok)throw new Error(await readApiError(res));serverState=await res.json();syncInputs()}catch(error){connectionLabel();toast(`后端不可用：${error.message||error}`)}}
async function loadServerProject(){if(location.protocol==='file:'){projectHydrated=true;return}try{const res=await fetch('/api/project');if(res.status===404){projectHydrated=true;scheduleProjectSave();return}if(!res.ok)throw new Error(await readApiError(res));const project=(await res.json()).state;state=normalizeProject(project);selectedPageIndex=Math.min(selectedPageIndex,Math.max(0,state.pages.length-1));localStorage.setItem(STORAGE,JSON.stringify(projectSnapshot()));projectHydrated=true;syncInputs();$('#saveState').textContent='已从本机后端恢复'}catch(error){projectHydrated=true;$('#saveState').textContent='后端项目读取失败，使用浏览器缓存';toast(`项目恢复失败：${error.message||error}`)}}
function collectParams({useCoords=true}={}){const chars=state.characters.filter(Boolean);const centers=chars.map((_,index)=>({x:chars.length===1?.5:.2+index*.6/(chars.length-1),y:.5}));const negative=state.negative.trim();return {params_version:4,width:dims[state.aspect][0],height:dims[state.aspect][1],scale:Number(state.guidance),sampler:state.sampler,steps:Number(state.steps),n_samples:Number(state.samples),seed:state.seed?Number(state.seed):Math.floor(Math.random()*4294967295),negative_prompt:negative,uc:negative,ucPreset:0,qualityToggle:true,legacy:false,legacy_v3_extend:false,add_original_image:true,cfg_rescale:0,noise_schedule:'karras',v4_prompt:{caption:{base_caption:state.prompt,char_captions:chars.map((char_caption,index)=>({char_caption,centers:[centers[index]]}))},use_coords:useCoords&&chars.length>1,use_order:true,legacy_uc:false},v4_negative_prompt:{caption:{base_caption:negative,char_captions:chars.map((_,index)=>({char_caption:negative,centers:[centers[index]]}))},use_coords:false,use_order:false,legacy_uc:false}}}
function unzipImages(buffer){try{const entries=unzipSync(new Uint8Array(buffer));const images=Object.entries(entries).filter(([name])=>/\.(png|webp|jpe?g)$/i.test(name)).map(([name,bytes])=>new Blob([bytes],{type:/\.png$/i.test(name)?'image/png':/\.webp$/i.test(name)?'image/webp':'image/jpeg'}));if(!images.length)throw new Error('压缩包中没有可用图片文件');return images}catch(error){throw new Error(`无法解包 NovelAI 图片结果：${error.message||error}`)}}
async function generateImage({prompt=state.prompt,characters=state.characters,title='基础出图',useCharacterCoords=true}={}){if(imageGenerationActive)throw new Error('已有图片任务正在生成，请等待当前任务结束后再提交。');if(!serverState.nai.configured){$('#settingsDialog').showModal();toast('请先在后端连接设置中保存 NovelAI Token');throw new Error('后端未配置 NovelAI Token')}const oldPrompt=state.prompt,oldChars=state.characters;state.prompt=prompt;state.characters=characters;const params=collectParams({useCoords:useCharacterCoords});state.prompt=oldPrompt;state.characters=oldChars;const button=$('#generateButton');imageGenerationActive=true;clearImageError();button.disabled=true;button.textContent='正在生成…';try{const res=await fetch('/api/generate/image',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/zip'},body:JSON.stringify({input:prompt,model:state.model,parameters:params})});if(!res.ok){let message=await readApiError(res);if(res.status===429){const retry=res.headers.get('Retry-After');message=`${message}${retry?`\n\n请等待 ${retry} 秒再继续。`:''}`}throw new Error(message)}const type=res.headers.get('content-type')||'';const blobs=type.includes('image/')?[await res.blob()]:await unzipImages(await res.arrayBuffer());const urls=blobs.map(blob=>URL.createObjectURL(blob));return {url:urls[0],urls,blobs,title,seed:params.seed}}catch(error){const message=error.message||'生成失败';showImageError(message);toast(message);throw error}finally{imageGenerationActive=false;button.disabled=false;button.innerHTML='<span>✦</span> 生成图片 <kbd>⌘ ↵</kbd>'}}
async function persistImageAsset(blob){const res=await fetch('/api/assets/image',{method:'POST',headers:{'Content-Type':blob.type||'image/png'},body:blob});if(!res.ok)throw new Error(await readApiError(res));const payload=await res.json();if(!persistedAssetUrl(payload.url))throw new Error('后端未返回有效素材地址');return payload.url}
async function persistImages(blobs){return Promise.all(blobs.map(persistImageAsset))}
async function basicGenerate(){try{const result=await generateImage();let urls;try{urls=await persistImages(result.blobs)}catch(error){urls=result.urls;toast(`图片已生成，但保存到本机失败：${error.message||error}`)}if(lastImageUrl&&lastImageUrl.startsWith('blob:'))URL.revokeObjectURL(lastImageUrl);lastImageUrl=urls[0];$('#generatedImage').src=urls[0];$('#generatedImage').hidden=false;$('#emptyArt').hidden=true;$('#generationMeta').textContent=`${dims[state.aspect].join(' × ')} · seed ${result.seed}`;$('#downloadImage').disabled=false;$('#useAsReference').disabled=false;state.assets.unshift(...urls.map((src,i)=>({src,title:`基础图${urls.length>1?` ${i+1}`:''} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`})));save();renderAssets();toast(urls.length>1?`已生成 ${urls.length} 张并保存到本机素材库`:'图片已生成并保存到本机素材库')}catch{}}
function getComicRoles(){const raw=state.comicCharacters.trim();if(!raw)return [];let entries=raw.split(/[；;\n]/).map(x=>x.trim()).filter(Boolean);if(entries.length===1&&!/[：:]/.test(raw))entries=raw.split(/[，,]/).map(x=>x.trim()).filter(Boolean);return entries.map((entry,index)=>{const match=entry.match(/[：:]/);const pivot=match?match.index:-1;const name=(pivot>=0?entry.slice(0,pivot):entry).trim();const appearance=(pivot>=0?entry.slice(pivot+1):'').trim();return {index:index+1,name:name||`角色 ${index+1}`,appearance}})}
function characterCaption(role){const caption=(role.appearance||role.name).trim();return /(?:^|,)\s*(?:\d+\s*)?(?:girl|boy)\b/i.test(caption)?caption:`girl, ${caption}`}
function roleGender(role){const caption=characterCaption(role);if(/(?:^|,)\s*(?:\d+\s*)?boy\b/i.test(caption))return 'boy';if(/(?:^|,)\s*(?:\d+\s*)?girl\b/i.test(caption))return 'girl';return 'character'}
function castCountTag(roles){const genders=roles.map(roleGender);const girls=genders.filter(gender=>gender==='girl').length;const boys=genders.filter(gender=>gender==='boy').length;if(girls===roles.length)return roles.length===1?'1girl, solo':`${roles.length}girls`;if(boys===roles.length)return roles.length===1?'1boy, solo':`${roles.length}boys`;return roles.length===1?'solo, 1character':`${roles.length} characters`}
function panelLayout(count){const layouts={2:{name:'two-panel split page',anchors:['Left','Right']},3:{name:'three-panel page with one top wide panel and two lower panels',anchors:['Top','Bottom-left','Bottom-right']},4:{name:'four-panel 2x2 grid',anchors:['Top-left','Top-right','Bottom-left','Bottom-right']},6:{name:'six-panel 2x3 grid',anchors:['Top-left','Top-center','Top-right','Bottom-left','Bottom-center','Bottom-right']}};return layouts[count]||{name:`${count}-panel page`,anchors:Array.from({length:count},(_,index)=>`Panel ${index+1}`)}}
function panelAnchor(index,count){return panelLayout(count).anchors[index]||`Panel ${index+1}`}
function withPanelAnchor(panel,index,count){const clean=panel.replace(/^\s*(top|left|right|top-left|top-center|top-right|bottom-left|bottom-center|bottom-right|panel\s+\d+)\s*[:;]\s*/i,'');return `${panelAnchor(index,count)}: ${clean}`}
function promptForPage(page,includeCharacterSheet=false){const roles=getComicRoles();const fallbackRoles=roles.length?roles:[{index:1,name:'Character 1',appearance:'girl'}];const panelCount=Math.max(1,(page.panels||[]).length);const layout=panelLayout(panelCount);const panels=(Array.isArray(page.panels)?page.panels:[]).map((panel,index)=>withPanelAnchor(panel,index,panelCount)).join(' ');const identity=fallbackRoles.length>1?`${fallbackRoles.map(role=>`Character ${role.index}`).join(' and ')} appear in every panel with consistent identities and clothing.`:'Character 1 remains visually consistent across all panels.';const anchors=`Layout: ${layout.name}; equal clean panel borders; anchors: ${layout.anchors.join(', ')}.`;const continuity=[state.continuityAnchor,page.continuity].filter(Boolean).join(' ');const base=`${castCountTag(fallbackRoles)}, ${panelCount}-panel manga-style page, ${anchors} ${state.comicStyle||''} ${panels} ${identity} ${continuity?`Continuity anchor: ${continuity}.`:''} ${page.pagePrompt||''}`.trim();if(!includeCharacterSheet)return base;const sheet=fallbackRoles.map(role=>`Character ${role.index}: ${characterCaption(role)}`).join('\n');return `${base}\n\n${sheet}`}
function parseCharacterPrompts(){const roles=getComicRoles();return roles.length?roles.map(characterCaption):state.characters.filter(Boolean)}
async function resolveComicCharacters(){const raw=state.comicCharacters.trim();if(!raw){toast('请先输入中文角色名');return}const button=$('#resolveCharacters');button.disabled=true;button.textContent='正在识别…';try{const res=await fetch('/api/resolve/characters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({characters:raw})});if(!res.ok)throw new Error(await readApiError(res));const resolved=(await res.json()).characters||[];const mapped=resolved.map(item=>{const label=item.input||item.english_name;const canonical=item.nai_character||[item.english_name,item.series&&`(${item.series})`].filter(Boolean).join(' ');return `${label}：${canonical}`}).filter(x=>!x.endsWith('：'));if(!mapped.length)throw new Error('未识别到可用角色');state.comicCharacters=mapped.join('；');$('#comicCharacters').value=state.comicCharacters;const uncertain=resolved.filter(item=>item.confidence!=='high').length;$('#characterResolveHint').textContent=uncertain?`已写入 ${mapped.length} 个映射；其中 ${uncertain} 个不确定，请检查后再生成。`:`已写入 ${mapped.length} 个英文名与出处映射，会同时提供给 LLM 和 NovelAI Character 字段。`;save();toast('角色英文名与出处已写入，可手动编辑')}catch(error){toast(error.message||'角色名称识别失败')}finally{button.disabled=false;button.textContent='识别英文名与出处'}}
async function generatePage(index){const page=state.pages[index];if(!page||page.loading)return;if(imageGenerationActive){toast('已有图片任务正在生成，请等待后再提交。');return}const issues=pagePromptReview(page);if(issues.length&&!confirm(`本页 Prompt 检查发现：${issues.join('；')}。仍要生成吗？`))return;page.loading=true;renderPages();try{const result=await generateImage({prompt:promptForPage(page),characters:parseCharacterPrompts(),title:`第 ${index+1} 页 · ${page.title}`,useCharacterCoords:state.characterPlacement==='left-right'});try{page.image=await persistImageAsset(result.blobs[0]);state.assets.unshift({src:page.image,title:`本子 · 第 ${index+1} 页`});toast(`第 ${index+1} 页已生成并保存到本机`)}catch(error){page.image=result.url;state.assets.unshift({src:result.url,title:`本子 · 第 ${index+1} 页`});toast(`第 ${index+1} 页已生成，但保存到本机失败：${error.message||error}`)}}catch{}finally{page.loading=false;save();renderPages();renderAssets()}}
async function generateAllPages(){if(!state.pages.length){toast('请先生成剧本');return}if(allPagesRunning){toast('全页生成任务正在运行，请勿重复提交。');return}const pending=state.pages.map((page,index)=>page.image?null:index).filter(index=>index!==null);if(!pending.length){toast('所有页面都已有图片；如需重绘，请点击对应页面的“生成本页”。');return}allPagesRunning=true;try{for(const index of pending)await generatePage(index)}finally{allPagesRunning=false}}
function localStoryboard(){const count=Number(state.pageCount), panels=Number(state.panelCount);const roles=getComicRoles();const lead='Character 1',partner=roles.length>1?'Character 2':'Character 1';const beats=[['发现信件','主角在海边车站发现一封褪色的信，故事开始出现异常。',[`wide shot, ${lead} standing beside an empty bench, deserted seaside station platform, sunset`,`upper body, ${lead} holding an old envelope in one hand, surprised expression, ocean light`,`close-up, ${lead}'s hand holding the handwritten letter, reflected light on paper`,`from behind, ${lead} looking down the railway tracks, wind across the platform`]],['约定同行','同伴赶到车站，两人决定按信中的线索同行。',[`wide shot, ${partner} running down the station stairs toward ${lead}, late afternoon`,`medium shot, ${lead} holding the letter toward ${partner}, both facing each other`,`close-up, ${lead} pointing at the timetable while ${partner} looks at the letter, old station clock`,`long shot, ${lead} and ${partner} running along the platform in the same direction, evening shadows`]],['追赶列车','线索指向远处列车，两人穿过夕照的站台。',[`low angle, distant train entering the platform, ${lead} and ${partner} at the platform edge`,`medium shot, ${lead} reaching one hand toward ${partner}, hands almost touching`,`from side, ${partner} holding ${lead}'s hand and pulling ${lead} forward, warm backlighting`,`wide shot, ${lead} and ${partner} running beside the rails, glowing sea beyond the platform`]],['未来的回信','列车离开后，信的最后一页揭示它来自未来。',[`medium shot, ${lead} and ${partner} sitting side by side by a train window`,`close-up, ${lead} holding the final page of the letter, sunset light through the window`,`upper body, ${lead} looking at ${partner} with a quiet smile, soft window light`,`wide shot, train moving across the sea horizon at sunset, ${lead} and ${partner} visible through the window`]]];return Array.from({length:count},(_,i)=>{const b=beats[i%beats.length];let directions=b[2];if(panels<directions.length)directions=directions.slice(0,panels);if(panels>directions.length)directions=[...directions,...Array.from({length:panels-directions.length},(_,j)=>`medium shot, ${lead} and ${partner} continuing along the station platform, evening light, connected moment ${j+1}`)];return {title:b[0],beat:b[1],continuity:state.continuityAnchor,panels:directions,pagePrompt:''}})}
function storyboardRoleBindings(){const roles=getComicRoles();return roles.length?roles.map(role=>`Character ${role.index} = ${role.name}; NovelAI Character field = ${characterCaption(role)}`).join('\n'):state.comicCharacters.trim()}
async function llmStoryboard(){if(!serverState.llm.configured)return null;const layout=panelLayout(Number(state.panelCount));const res=await fetch('/api/generate/script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({synopsis:state.synopsis,characters:storyboardRoleBindings(),visual_anchor:state.comicStyle,continuity_anchor:state.continuityAnchor,layout:`${layout.name}; panel anchors: ${layout.anchors.join(', ')}`,pages:Number(state.pageCount),panels:Number(state.panelCount)})});if(res.status===204)return null;if(!res.ok)throw new Error(await readApiError(res));const json=await res.json();if(!Array.isArray(json.pages)||json.pages.length!==Number(state.pageCount))throw new Error('剧本文本模型未返回请求的准确页数');return json.pages.map(page=>normalizePage(page))}
async function buildScript(){const b=$('#generateScript');clearLlmError();b.disabled=true;b.textContent='正在规划分镜…';try{state.pages=await llmStoryboard()||localStoryboard();save();renderPages();renderPageTree();toast(serverState.llm.configured?'剧本文本模型已生成分镜':'已生成本地分镜初稿，可直接编辑')}catch(e){const message=e.message||'剧本生成失败';showLlmError(message);toast(message)}finally{b.disabled=false;b.innerHTML='<span>✦</span> 生成剧本和分镜'}}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>{if(url.startsWith('blob:'))URL.revokeObjectURL(url)},1000)}
function safeFileName(value='page'){return value.replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').trim().slice(0,80)||'page'}
function imageExtension(mime=''){return mime.includes('webp')?'webp':mime.includes('jpeg')?'jpg':'png'}
async function downloadComicPackage(){if(!state.pages.length){toast('请先生成剧本');return}const button=$('#downloadComicZip');button.disabled=true;button.textContent='正在打包…';try{const files={};const missingImages=[];const manifest={project:state.projectName,exportedAt:new Date().toISOString(),pages:[]};for(let index=0;index<state.pages.length;index++){const page=state.pages[index];const prefix=String(index+1).padStart(2,'0');const name=safeFileName(page.title||`page-${prefix}`);const prompt=promptForPage(page,true);files[`prompts/${prefix}-${name}.txt`]=strToU8(prompt);const item={page:index+1,title:page.title,beat:page.beat,panels:page.panels,prompt,imageIncluded:false};if(page.image){try{const response=await fetch(page.image);if(!response.ok)throw new Error(`${response.status}`);const blob=await response.blob();files[`pages/${prefix}-${name}.${imageExtension(blob.type)}`]=new Uint8Array(await blob.arrayBuffer());item.imageIncluded=true}catch(error){missingImages.push(`第 ${index+1} 页：图片无法读取（${error.message||error}）`)}}else{missingImages.push(`第 ${index+1} 页：尚未生成图片`)}manifest.pages.push(item)}files['storyboard.json']=strToU8(JSON.stringify(manifest,null,2));files['README.txt']=strToU8(`NAI Flow 本子导出包\n\n包含：\n- pages/: 已成功读取的页面图片\n- prompts/: 每页完整 NovelAI V5 提示词（含 Character 字段）\n- storyboard.json: 剧本、分镜和导出清单\n\n${missingImages.length?`未包含图片：\n${missingImages.join('\n')}`:'所有页面图片均已包含。'}\n`);const archive=zipSync(files,{level:6});download(URL.createObjectURL(new Blob([archive],{type:'application/zip'})),`${safeFileName(state.projectName||'nai-flow')}-comic.zip`);toast(`本子包已下载：${state.pages.length-missingImages.length}/${state.pages.length} 页图片，全部提示词已附带`)}catch(error){toast(`打包失败：${error.message||error}`)}finally{button.disabled=false;button.textContent='打包下载'}}
function exportProject(){const blob=new Blob([JSON.stringify({...state,assets:[]},null,2)],{type:'application/json'});download(URL.createObjectURL(blob),`${state.projectName||'nai-flow'}.json`)}
function formatPrompt(){state.prompt=state.prompt.replace(/\s*,\s*/g,', ').replace(/\n{3,}/g,'\n\n').trim();$('#promptInput').value=state.prompt;updateParameterLabels();save();toast('已整理逗号与段落结构')}
function setSettingsFeedback(message='',error=false){const feedback=$('#settingsFeedback');feedback.hidden=!message;feedback.textContent=message;feedback.style.color=error?'#ef9eaa':'#85d8b2'}
function editStoryboard(index){const page=state.pages[index];if(!page)return;const draft=JSON.stringify({title:page.title,beat:page.beat,continuity:page.continuity,panels:page.panels},null,2);const value=prompt('编辑标题、剧情、连续性和每格分镜（JSON）',draft);if(value===null)return;try{const parsed=JSON.parse(value);const updated=normalizePage({...page,...parsed},{allowBlob:true});if(!updated.panels.length)throw new Error('至少需要一格分镜');state.pages[index]=updated;save();renderPages();renderPageTree();toast(page.image?'分镜已更新；当前页面图保留，可按需重新生成本页。':'分镜已更新')}catch(error){toast(`分镜格式无效：${error.message||error}`)}}
function assetFilename(src){try{const url=new URL(src,location.origin);const name=url.pathname.split('/').pop()||'';return /^[a-f0-9]{32}\.(png|webp|jpg)$/i.test(name)?name:''}catch{return ''}}
async function deleteSavedAsset(src){const filename=assetFilename(src);if(!filename)return;const response=await fetch(`/api/assets/${filename}`,{method:'DELETE'});if(!response.ok&&response.status!==404)throw new Error(await readApiError(response))}
async function clearAllAssets(){if(!confirm('将永久删除本机素材库与页面预览图片，且无法恢复。是否继续？'))return;const urls=[...state.assets.map(asset=>asset.src),...state.pages.map(page=>page.image)].filter(persistedAssetUrl);state.assets=[];state.pages.forEach(page=>{page.image=''});save();renderAssets();renderPages();const results=await Promise.allSettled([...new Set(urls)].map(deleteSavedAsset));const failures=results.filter(result=>result.status==='rejected').length;toast(failures?`预览已清空，但有 ${failures} 个本机图片删除失败。`:'已清空本机素材库和页面预览')}
function setupEvents(){
  $('#testNaiConnection').onclick=async()=>{const button=$('#testNaiConnection');button.disabled=true;button.textContent='正在测试…';setSettingsFeedback('正在使用当前填写的 Token 和接口测试连接…');try{const res=await fetch('/api/settings/test/nai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nai:{token:$('#naiToken').value.trim()||undefined,endpoint:$('#naiEndpoint').value.trim()}})});if(!res.ok)throw new Error(await readApiError(res));setSettingsFeedback((await res.json()).detail)}catch(error){setSettingsFeedback(error.message||'NovelAI 连接测试失败',true)}finally{button.disabled=false;button.textContent='测试 NovelAI 连接（不扣额度）'}};
  $$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#promptInput').oninput=e=>{state.prompt=e.target.value;updateParameterLabels();save()};$('#negativeInput').oninput=e=>{state.negative=e.target.value;save()};
  [['modelSelect','model'],['aspectSelect','aspect'],['sampleCount','samples'],['steps','steps'],['guidance','guidance'],['sampler','sampler'],['seed','seed']].forEach(([id,key])=>$('#'+id).oninput=e=>{state[key]=e.target.value;updateParameterLabels();save()});
  $('#characterList').oninput=e=>{if(e.target.dataset.char!==undefined){state.characters[Number(e.target.dataset.char)]=e.target.value;save()}};$('#characterList').onclick=e=>{const i=e.target.dataset.deleteChar;if(i!==undefined){state.characters.splice(Number(i),1);renderCharacters();save()}};$('#addCharacter').onclick=()=>{state.characters.push('girl, ');renderCharacters();save()};
  $('#generateButton').onclick=basicGenerate;$('#randomSeed').onclick=()=>{state.seed=randomSeed();$('#seed').value=state.seed;save()};$('#resetParameters').onclick=()=>{Object.assign(state,{model:defaultState.model,aspect:defaultState.aspect,samples:'1',steps:28,guidance:5,sampler:'k_euler_ancestral',seed:'',variety:false,negative:''});syncInputs();save();toast('参数已重置')};$('#formatPrompt').onclick=formatPrompt;
  $('#downloadImage').onclick=()=>lastImageUrl&&download(lastImageUrl,'nai-flow.png');$('#useAsReference').onclick=()=>toast('参考图模式预留：当前版本已保留结果，后续可接 i2i 参数');
  $('#synopsisInput').oninput=e=>{state.synopsis=e.target.value;save()};$('#comicCharacters').oninput=e=>{state.comicCharacters=e.target.value;save()};$('#comicStyle').oninput=e=>{state.comicStyle=e.target.value;save()};$('#continuityAnchor').oninput=e=>{state.continuityAnchor=e.target.value;save()};$('#characterPlacement').onchange=e=>{state.characterPlacement=e.target.value;save()};$('#resolveCharacters').onclick=resolveComicCharacters;$('#pageCount').onchange=e=>{state.pageCount=e.target.value;save()};$('#panelCount').onchange=e=>{state.panelCount=e.target.value;save()};$('#generateScript').onclick=buildScript;$('#regenerateScript').onclick=buildScript;$('#downloadComicZip').onclick=downloadComicPackage;$('#generateAllPages').onclick=generateAllPages;
  $('#pagesGrid').onclick=e=>{const g=e.target.dataset.generatePage,c=e.target.dataset.copyPage,edit=e.target.dataset.editPage,editStoryboardIndex=e.target.dataset.editStoryboard;if(g!==undefined)generatePage(Number(g));if(c!==undefined){navigator.clipboard.writeText(promptForPage(state.pages[Number(c)],true));toast('整页提示词与角色表已复制')}if(editStoryboardIndex!==undefined)editStoryboard(Number(editStoryboardIndex));if(edit!==undefined){const p=state.pages[Number(edit)],value=prompt('编辑本页附加提示词（将附在分格描述之后）',p.pagePrompt||'');if(value!==null){p.pagePrompt=value;save();renderPages()}}};
  $('#pageTree').onclick=e=>{const index=Number(e.target.dataset.pageSelect);if(!Number.isInteger(index)||!state.pages[index])return;selectedPageIndex=index;renderPageTree();setView('comic');requestAnimationFrame(()=>document.querySelector(`[data-page-card="${index}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}))};
  $('#openSettings').onclick=()=>{setSettingsFeedback();$('#settingsDialog').showModal()};$('#showHelp').onclick=()=>$('#helpDialog').showModal();$$('.settings-tab').forEach(button=>button.onclick=()=>{$$('.settings-tab').forEach(tab=>tab.classList.toggle('active',tab===button));$$('.settings-content').forEach(content=>content.classList.toggle('active',content.id===button.dataset.settings+'Settings'));setSettingsFeedback()});$('#saveSettings').onclick=async()=>{setSettingsFeedback('正在保存…');try{const res=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nai:{token:$('#naiToken').value.trim()||undefined,endpoint:$('#naiEndpoint').value.trim()},llm:{token:$('#llmToken').value.trim()||undefined,endpoint:$('#llmEndpoint').value.trim(),model:$('#llmModel').value.trim()}})});if(!res.ok)throw new Error(await readApiError(res));serverState=await res.json();syncInputs();$('#settingsDialog').close();toast('连接设置已保存到本机后端')}catch(error){setSettingsFeedback(error.message||'保存设置失败',true)}};
  $('#renameProject').onclick=()=>{const v=prompt('项目名称',state.projectName);if(v?.trim()){state.projectName=v.trim();syncInputs();save()}};$('#addPage').onclick=()=>{state.pages.push({title:'新页面',beat:'等待补充分镜内容。',panels:['Panel 1 visual direction','Panel 2 visual direction','Panel 3 visual direction','Panel 4 visual direction'],pagePrompt:''});selectedPageIndex=state.pages.length-1;save();renderPages();renderPageTree()};$('#clearAssets').onclick=clearAllAssets;
  $('#exportProject').onclick=exportProject;$('#importProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());delete imported.settings;state=normalizeProject(imported);selectedPageIndex=0;save();syncInputs();toast('项目已导入（图片不会随 JSON 导入）')}catch(error){toast(`项目文件无效：${error.message||error}`)}finally{e.target.value=''}};
  $('#assetGrid').onclick=e=>{const i=e.target.dataset.downloadAsset;if(i!==undefined){const asset=state.assets.filter(item=>isSafeImageUrl(item.src))[Number(i)];if(asset)download(asset.src,'nai-flow-asset.png')}};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();basicGenerate()}});
}
syncInputs();setupEvents();refreshBackendStatus();loadServerProject();
